source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FACoreData_Example', :exclusive => true do
  pod "DStack", :path => "../"
end

target 'FACoreData_Tests', :exclusive => true do
  pod "DStack", :path => "../"

#pod 'Quick'
#pod 'Nimble'
#pod 'FBSnapshotTestCase'
# pod 'Nimble-Snapshots'
end
